# Image Processing & Analysis Assignment #2

### You will need to perform the following Tasks:  

#### Using `image_cell.tif`
**Task 1.**  
    
   From the downloaded image (`img`; file = `image_cell.tif`), make an image `img1` from just the red channel (channel 0) at time point 23 of the tensor [T,Y,X,C]  

**Task 2.**  

   Using `img1`, create a new image `img2` where values less than than the mean are set to the background value (calculated as the minimum intensity value in the image).  

**Task 3.**  

   - Set `img2[0:20,0:20] = np.amax(img2)` (Make a white box in the image to more easily visualize the transformation)  
   - Compress `img2` in half, rotate it 30 degrees clockwise, and translate its `(0,0)` to `(dx,dy)=(200,100)`  
   - Save resulting image as `img3`  
   - Plot `img3` side-by-side with `img2`  

**Task 4.**  **EXTRA CREDIT**  

   - Build a slider function to display different frames of an RGB image over time.  
   - Consider 3 subplots for: 'RED', 'GREEN', 'BLUE' channels
   - Make the interactive slider for time: int with range 0 to the number of frames in video. 

-----  
#### Using `FISH_example.tif`
**Task 5.**  
    - Make a slice of `img_FISH` and save as `img_FISH_slice` using: `Z=10`, `Y=120:350`, `X=50:250`  
    - Apply a Gaussian filter to `img_FISH_slice` with `sigma=1` and save it as `img_gaussian_filter_simga_1`
    - Make difference of Gaussians filter of `img_FISH_slice` using `low_sigma=1` and `high_sigma=5` and `img_diff_gaussians`
    - Plot all 3 images side-by-side (in 3 subplots). 

## Loading libraries

In [1]:
# Load libraries
import matplotlib.pyplot as plt # Library used for plotting
from matplotlib.patches import Rectangle # module to plot a rectangle in the image
import numpy as np # library for array manipulation
import seaborn as sn # plotting library
import pandas as pd # data frames library
import tifffile # library to store numpy arrays in TIFF
import skimage # Library for image manipulation
from skimage.io import imread # sublibrary from skimage
from scipy.ndimage import gaussian_filter
from skimage.filters import difference_of_gaussians
from skimage import transform
import os

In [2]:
import ipywidgets as widgets # Importing library
from ipywidgets import interact, interactive, HBox, Layout, VBox #  importing modules and functions.

## Download image files
Do NOT push the image files to your GitHub repository! This notebook with the rendered images is okay.

In [3]:
if not os.path.exists("./FISH_example.tif"):
   !wget -O FISH_example.tif "https://www.dropbox.com/s/669j6zags6xd7gr/FISH_example.tif?dl=1"

In [4]:
if not os.path.exists("./image_cell.tif"):
    !wget -O image_cell.tif https://ndownloader.figshare.com/files/26751209

In [5]:
# reading the image and saving as variable img
img = imread('./image_cell.tif')

# Task 1
# add your code here
img1 = [] # change as appropriate

# Task 2
img2 = [] # change as appropriate

# plot the results
# Side-by-side comparizon


### Task 3.

In [6]:
# Make a white box

#  transformation matrix
tform = transform.SimilarityTransform( # modify as appropriate
    # float, scaling value
    # Rotation angle in counter-clockwise direction as radians. pi/180 rad = 1 degrees
    # (dx, dy) values for translation
)      
print('Transformation matrix : \n', tform.params , '\n')

# Apply the transformation
img3 = [] # modify as appropriate

# Side-by-side comparizon


Transformation matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



### Task 4. (extra credit)

In [7]:
def video_viewer(time):
    '''
    This function is intended to display different frames of an RGB image over time by sliding through time  [T,Y,X,C].
    3 subplots for: 'RED', 'GREEN', 'BLUE' channels
    time: int with range 0 to the number of frames in video.
    '''   
    # modify as appropriate


# The code below will test your video_viewer function
# Defining an interactive plot
interactive_plot = interactive(video_viewer,
                               time = widgets.IntSlider(min=0,max=img.shape[0]-1,step=1,value=0,description='Time'))       # time slider parameters
# Creates the controls
controls = HBox(interactive_plot.children[:-1], layout = Layout(flex_flow='row wrap'))

# Creates the outputs
output = interactive_plot.children[-1]

# Display the controls and output as an interactive widget
display(VBox([controls, output]))

### Task 5.

In [8]:
# importing the FISH image as variable img_FISH
img_FISH = imread('./FISH_example.tif') 

# Make a slice of the sequence of images
img_FISH_slice = [] # modify as appropriate
img_gaussian_filter_simga_1 = [] # modify as appropriate
img_diff_gaussians = [] # modify as appropriate


In [9]:
# The code below should plot your results for Task 5 once the variables are defined correctly
if img_diff_gaussians != []:
    fig, ax = plt.subplots(1,3, figsize=(20, 10))
    ax[0].imshow(img_FISH_slice,cmap='gray')
    ax[0].set(title='sliced img FISH z = 10, original')
    ax[1].imshow(img_gaussian_filter_simga_1,cmap='gray')
    ax[1].set(title='Gaussian kernel $\sigma$ =1')
    ax[2].imshow(img_diff_gaussians,cmap='gray')
    ax[2].set(title='diff Gaussian kernel $\sigma$ =1,3')
    plt.show()